<?php
$editing = isset($page);
$pageContent = old('content', $editing ? ($page->content ?? []) : []);
?>
<form method="POST" action="<?php echo e($editing?route('admin.pages.update',$page):route('admin.pages.store')); ?>" class="rounded-lg border border-[#EBEFEA] bg-white p-[18px] grid gap-3 [&_label]:grid [&_label]:gap-1.5 [&_input]:rounded-md [&_input]:border [&_input]:border-[#DDE2DF] [&_input]:bg-white [&_input]:px-2.5 [&_input]:py-2 [&_input]:text-sm [&_textarea]:min-h-[100px] [&_textarea]:rounded-md [&_textarea]:border [&_textarea]:border-[#DDE2DF] [&_textarea]:bg-white [&_textarea]:px-2.5 [&_textarea]:py-2 [&_textarea]:text-sm [&_select]:rounded-md [&_select]:border [&_select]:border-[#DDE2DF] [&_select]:bg-white [&_select]:px-2.5 [&_select]:py-2 [&_select]:text-sm"><?php echo csrf_field(); ?> <?php if($editing): ?><?php echo method_field('PUT'); ?><?php endif; ?>
<?php $__currentLoopData = \Illuminate\Support\Arr::dot($pageContent); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key => $value): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
<?php if(!in_array($key, ['blocks.0.type', 'blocks.0.data.text']) && is_scalar($value)): ?>
<input type="hidden" name="content[<?php echo e(str_replace('.', '][', $key)); ?>]" value="<?php echo e($value); ?>">
<?php endif; ?>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
<label>Title<input name="title" value="<?php echo e(old('title',$editing?$page->title:'')); ?>" required></label><label>Slug<input name="slug" value="<?php echo e(old('slug',$editing?$page->slug:'')); ?>"></label><label>Body<input type="hidden" name="content[blocks][0][type]" value="<?php echo e(data_get($pageContent, 'blocks.0.type', 'paragraph')); ?>"><textarea id="page-body" name="content[blocks][0][data][text]" rows="18"><?php echo e(old('content.blocks.0.data.text', data_get($editing ? $page->content : [], 'blocks.0.data.text', ''))); ?></textarea></label><label>Status<select name="status"><option value="draft" <?php if(old('status',$editing?$page->status:'draft')==='draft'): echo 'selected'; endif; ?>>Draft</option><option value="published" <?php if(old('status',$editing?$page->status:'draft')==='published'): echo 'selected'; endif; ?>>Published</option></select></label><label>SEO Title<input name="seo_title" value="<?php echo e(old('seo_title',$editing?$page->seo_title:'')); ?>"></label><label>SEO Description<textarea name="seo_description"><?php echo e(old('seo_description',$editing?$page->seo_description:'')); ?></textarea></label><button class="inline-flex h-11 cursor-pointer items-center justify-center gap-2 rounded-md border border-transparent px-3.5 text-sm font-medium no-underline transition bg-[#526A5A] text-white hover:bg-[#293C32]">Save Page</button></form><?php /**PATH /Users/ferdy/project-fl/vet-cms/backend/resources/views/admin/pages/_form.blade.php ENDPATH**/ ?>