<?php $__env->startSection('title','New Content · Content Studio'); ?>
<?php $__env->startSection('breadcrumb','New Content'); ?>
<?php $__env->startSection('content'); ?>
<?php if(!request()->has('type')): ?>
<section class="mx-auto max-w-[980px]"><div class="mb-7 flex flex-col items-start justify-between gap-6 lg:flex-row"><div><span class="text-[10px] font-semibold tracking-[0.09em] text-[#526A5A]">START WITH THE RIGHT SHAPE</span><h1>What would you like to create?</h1><p>Choose a writing format. You can still adapt the structure inside the editor.</p></div></div><div class="grid grid-cols-1 gap-4 md:grid-cols-2"><?php $__currentLoopData = [['article','ARTICLE','Long-form writing and educational content.','A'],['clinical_case','CLINICAL CASE','Structured case documentation, findings, and clinical reflection.','C'],['quick_note','QUICK NOTE','Short observations, conference takeaways, or field notes.','N'],['story','STORY','Personal experience, career moments, and storytelling.','S']]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><a href="<?php echo e(route('admin.posts.create',['type'=>$item[0]])); ?>" class="flex gap-[18px] rounded-[10px] border border-[#DDE2DF] bg-white p-6 text-[#181D1A] no-underline transition duration-200 hover:-translate-y-0.5 hover:border-[#8FA58F] [&_h2]:my-2 [&_h2]:font-['Newsreader'] [&_h2]:text-[26px] [&_h2]:font-medium [&_p]:text-xs [&_p]:leading-relaxed [&_p]:text-[#70766F] [&_strong]:text-[11px] [&_strong]:text-[#526A5A]"><span class="grid size-12 place-items-center rounded-[10px] bg-[#E7ECE5] font-['Newsreader'] text-xl font-semibold text-[#526A5A]"><?php echo e($item[3]); ?></span><div><span class="text-[10px] font-semibold tracking-[0.09em] text-[#526A5A]"><?php echo e($item[1]); ?></span><h2><?php echo e(ucwords(str_replace('_',' ',$item[0]))); ?></h2><p><?php echo e($item[2]); ?></p><strong>Start writing →</strong></div></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div></section>
<?php else: ?>
<?php echo $__env->make('admin.posts._editor',['post'=>null], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?>
<?php endif; ?>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('admin.layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH /Users/ferdy/project-fl/vet-cms/backend/resources/views/admin/posts/create.blade.php ENDPATH**/ ?>