@extends('admin.layouts.app')
@section('title','New Content · Content Studio')
@section('breadcrumb','New Content')
@section('content')
@if(!request()->has('type'))
<section class="mx-auto max-w-[980px]"><div class="mb-7 flex flex-col items-start justify-between gap-6 lg:flex-row"><div><span class="text-[13px] font-semibold tracking-[0.09em] text-[#526A5A]">START WITH THE RIGHT SHAPE</span><h1>What would you like to create?</h1><p>Choose a writing format. You can still adapt the structure inside the editor.</p></div></div><div class="grid grid-cols-1 gap-4 md:grid-cols-2">@foreach([['article','ARTICLE','Long-form writing and educational content.','A'],['clinical_case','CLINICAL CASE','Structured case documentation, findings, and clinical reflection.','C'],['quick_note','QUICK NOTE','Short observations, conference takeaways, or field notes.','N'],['story','STORY','Personal experience, career moments, and storytelling.','S']] as $item)<a href="{{ route('admin.posts.create',['type'=>$item[0]]) }}" class="flex gap-[18px] rounded-[10px] border border-[#DDE2DF] bg-white p-6 text-[#181D1A] no-underline transition duration-200 hover:-translate-y-0.5 hover:border-[#8FA58F] [&_h2]:my-2 [&_h2]:font-['Newsreader'] [&_h2]:text-[26px] [&_h2]:font-medium [&_p]:text-sm [&_p]:leading-relaxed [&_p]:text-[#545F57] [&_strong]:text-[14px] [&_strong]:text-[#526A5A]"><span class="grid size-12 place-items-center rounded-[10px] bg-[#E7ECE5] font-['Newsreader'] text-xl font-semibold text-[#526A5A]">{{ $item[3] }}</span><div><span class="text-[13px] font-semibold tracking-[0.09em] text-[#526A5A]">{{ $item[1] }}</span><h2>{{ ucwords(str_replace('_',' ',$item[0])) }}</h2><p>{{ $item[2] }}</p><strong>Start writing →</strong></div></a>@endforeach</div></section>
@else
@include('admin.posts._editor',['post'=>null])
@endif
@endsection