@php
$editing = isset($page);
$pageContent = old('content', $editing ? ($page->content ?? []) : []);
@endphp
<form method="POST" action="{{ $editing?route('admin.pages.update',$page):route('admin.pages.store') }}" class="rounded-lg border border-[#EBEFEA] bg-white p-[18px] grid gap-3 [&_label]:grid [&_label]:gap-1.5 [&_input]:rounded-md [&_input]:border [&_input]:border-[#DDE2DF] [&_input]:bg-white [&_input]:px-2.5 [&_input]:py-2 [&_input]:text-sm [&_textarea]:min-h-[100px] [&_textarea]:rounded-md [&_textarea]:border [&_textarea]:border-[#DDE2DF] [&_textarea]:bg-white [&_textarea]:px-2.5 [&_textarea]:py-2 [&_textarea]:text-sm [&_select]:rounded-md [&_select]:border [&_select]:border-[#DDE2DF] [&_select]:bg-white [&_select]:px-2.5 [&_select]:py-2 [&_select]:text-sm">@csrf @if($editing)@method('PUT')@endif
@foreach(\Illuminate\Support\Arr::dot($pageContent) as $key => $value)
@if(!in_array($key, ['blocks.0.type', 'blocks.0.data.text']) && is_scalar($value))
<input type="hidden" name="content[{{ str_replace('.', '][', $key) }}]" value="{{ $value }}">
@endif
@endforeach
<label>Title<input name="title" value="{{ old('title',$editing?$page->title:'') }}" required></label><label>Slug<input name="slug" value="{{ old('slug',$editing?$page->slug:'') }}"></label><label>Body<input type="hidden" name="content[blocks][0][type]" value="{{ data_get($pageContent, 'blocks.0.type', 'paragraph') }}"><textarea id="page-body" name="content[blocks][0][data][text]" rows="18">{{ old('content.blocks.0.data.text', data_get($editing ? $page->content : [], 'blocks.0.data.text', '')) }}</textarea></label><label>Status<select name="status"><option value="draft" @selected(old('status',$editing?$page->status:'draft')==='draft')>Draft</option><option value="published" @selected(old('status',$editing?$page->status:'draft')==='published')>Published</option></select></label><label>SEO Title<input name="seo_title" value="{{ old('seo_title',$editing?$page->seo_title:'') }}"></label><label>SEO Description<textarea name="seo_description">{{ old('seo_description',$editing?$page->seo_description:'') }}</textarea></label><button class="inline-flex h-11 cursor-pointer items-center justify-center gap-2 rounded-md border border-transparent px-3.5 text-sm font-medium no-underline transition bg-[#526A5A] text-white hover:bg-[#293C32]">Save Page</button></form>